DROP TABLE Verkauf CASCADE CONSTRAINTS;

DROP TABLE Zeit CASCADE CONSTRAINTS;
DROP TABLE Produkt CASCADE CONSTRAINTS;
DROP TABLE Kunde CASCADE CONSTRAINTS;
DROP TABLE Verkäufer CASCADE CONSTRAINTS;

DROP TABLE Verkauf_2DC CASCADE CONSTRAINTS;